#!/usr/bin/env bash

if [ -z "$HOMEBREW_REPOSITORY" ]; then
     /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
brew install \
     amber \
     fzf \
     go \
     git-delta \
     helix \
     tmux

mkdir -p ~/.config
if [[ ! -d ~/.config/helix ]]; then
     git clone git@github.com:crockeo/helix-config ~/.config/helix
fi

if [[ ! -d ~/.emacs.d ]]; then
     git clone git@github.com:crockeo/.emacs.d ~/.emacs.d
fi
