#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if [ -z "${HOMEBREW_REPOSITORY:-}" ]; then
     /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
/opt/homebrew/bin/brew install \
     ag \
     cmake \
     fd \
     fzf \
     git-delta \
     helix \
     neovim \
     raycast \
     ripgrep \
     tmux \
     zoxide

mkdir -p ~/.config
if [[ ! -d ~/.config/helix ]]; then
     git clone git@github.com:crockeo/helix-config ~/.config/helix
fi

# Configuring some macOS things that I like:
#
# - Open + close the dock instantly.
# - Make the keyboard repeat more quickly.
# - Make the keyboard start repeating more quickly.
echo >&2 "Configuring dock to appear instantly..."
defaults write com.apple.dock autohide-delay -int 0
defaults write com.apple.dock autohide-time-modifier -int 0
killall Dock
echo >&2 "Done!"

echo >&2 "Configuring keyboard repeat rate..."
defaults write -g InitialKeyRepeat -int 15
defaults write -g KeyRepeat -int 2
echo >&2 "Done! You'll have to log out and back in for this to take effect."
