#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if [ -z "${HOMEBREW_REPOSITORY:-}" ]; then
     /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
/opt/homebrew/bin/brew install \
     ag \
     cmake \
     fd \
     fzf \
     git-delta \
     go \
     helix \
     ripgrep \
     tmux \
     zoxide

mkdir -p ~/.config
if [[ ! -d ~/.config/helix ]]; then
     git clone git@github.com:crockeo/helix-config ~/.config/helix
fi
