#!/usr/bin/env python3
import subprocess


def main() -> None:
    branches = subprocess.check_output(
        ("git", "--no-pager", "branch"), text=True
    ).strip()
    branches_to_remove = []
    for branch in branches.splitlines():
        branch = branch.strip()
        if branch.startswith("*") or branch.startswith("+"):
            continue
        branches_to_remove.append(branch)
    subprocess.check_call(("git", "branch", "--delete", "--force", *branches_to_remove))


if __name__ == "__main__":
    main()
