#!/usr/bin/env python3
import subprocess
import sys


def main() -> None:
    filters = sys.argv[1:]
    branches = subprocess.check_output(
        ("git", "--no-pager", "branch"), text=True
    ).strip()
    branches_to_remove = []
    for branch in branches.splitlines():
        branch = branch.strip()
        if branch.startswith("*") or branch.startswith("+"):
            continue
        if filters:
            for filter in filters:
                if filter in branch:
                    break
            else:
                continue
        branches_to_remove.append(branch)
    if not branches_to_remove:
        print("No branches to remove.")
        return
    subprocess.check_call(("git", "branch", "--delete", "--force", *branches_to_remove))


if __name__ == "__main__":
    main()
