#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sqlite3
import subprocess
import sys
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Generator, Sequence


BLUE = "\033[94m"
GREEN = "\033[92m"
RED = "\033[91m"
RESET = "\033[0m"


def run(args: Sequence[str], *, cwd: Path | None = None) -> None:
    try:
        subprocess.check_call(
            args,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            cwd=cwd,
            text=True,
        )
    except subprocess.CalledProcessError as e:
        rendered_args = " ".join(args)
        raise SystemExit(
            f"{RED}"
            f"Subprocess failed to execute: {rendered_args}\n"
            f"stdout: {e.stdout}\n\n"
            f"stderr: {e.stderr}\n\n"
            f"{RESET}"
        )


@contextmanager
def current_repo_state(repo_root: Path) -> Generator[None, None, None]:
    current_branch = get_current_branch(repo_root)
    # TODO: how to stash + pop a named patch so that
    # i know i'm always restoring from the right place?
    run(("git", "stash"), cwd=repo_root)
    try:
        yield
    finally:
        run(("git", "checkout", current_branch), cwd=repo_root)
        run(("git", "stash", "pop"), cwd=repo_root)


def find_repo_root(dir_path: Path) -> Path:
    original_dir_path = dir_path
    while dir_path:
        if dir_path == dir_path.parent:
            break
        if (dir_path / ".git").exists():
            return dir_path
        dir_path = dir_path.parent
    raise SystemExit(
        f"{RED}"
        f"Failed to find repo root for: {original_dir_path}\n"
        "Is it inside of a Git repository?"
        f"{RESET}"
    )


def get_current_branch(repo_root: Path) -> str:
    output = subprocess.check_output(
        ("git", "rev-parse", "--symbolic-full-name", "HEAD"),
        cwd=repo_root,
        text=True,
    )
    output = output.strip()
    if not output.startswith("refs/heads/"):
        raise SystemExit(
            f"{RED}"
            f"Failed to get current branch for: {repo_root}\n"
            "Is there a branch checked out?"
            f"{RESET}"
        )
    return output[len("refs/heads/") :]


def rebase(repo_root: Path, branch: str, onto: str, since: str | None = None) -> None:
    args: tuple[str, ...]
    if since is not None:
        args = ("git", "rebase", "--onto", onto, since, branch)
    else:
        args = ("git", "rebase", onto, branch)
    run(args, cwd=repo_root)


def get_db(repo_root: Path) -> sqlite3.Connection:
    db = sqlite3.connect(repo_root / ".git" / "diamond.sqlite3")
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS branches (
            name TEXT PRIMARY KEY,
            parent TEXT
        )
        """
    )
    return db


@dataclass(frozen=True)
class Branch:
    name: str
    parent: str | None


def get_root_branch(db: sqlite3.Connection) -> str | None:
    root_branch: tuple[str] | None = db.execute(
        "SELECT name FROM branches WHERE parent IS NULL"
    ).fetchone()
    if root_branch is None:
        return None
    return root_branch[0]


def get_branches_in_stack(db: sqlite3.Connection, branch: str) -> list[Branch]:
    cursor = db.execute(
        """
        WITH RECURSIVE
          stack_branches(name, parent, level) AS (
            VALUES(?, ?, 0)

            UNION

            SELECT branches.name, branches.parent, stack_branches.level + 1
            FROM branches, stack_branches
            WHERE branches.parent = stack_branches.name

            UNION

            SELECT branches.name, branches.parent, stack_branches.level - 1
            FROM branches, stack_branches
            WHERE stack_branches.parent = branches.name
              AND branches.parent IS NOT NULL
          )
        SELECT DISTINCT name, parent
        FROM stack_branches
        WHERE name <> parent
        ORDER BY level ASC
        """,
        (branch, branch),
    )
    branches = []
    for name, parent in cursor.fetchall():
        branches.append(
            Branch(
                name=name,
                parent=parent,
            )
        )
    return branches


@dataclass
class Context:
    branch: str
    db: sqlite3.Connection
    repo_root: Path


def create(ctx: Context) -> None:
    root_branch = get_root_branch(ctx.db)
    current_branch = get_current_branch(ctx.repo_root)

    if ctx.branch != current_branch:
        if root_branch is None:
            raise SystemExit(
                f"{RED}"
                "Cannot create new branch until root is created.\n"
                "Create root by running:\n"
                "  dmd create  (with no branch)"
                f"{RESET}"
            )

        run(("git", "checkout", "-b", ctx.branch))
        ctx.db.execute(
            """
            INSERT OR REPLACE INTO branches (
                name,
                parent,
            ) VALUES (
                ?,
                ?
            )
            """,
            (current_branch, ctx.branch),
        )
        return

    if ctx.branch == current_branch:
        if root_branch is None:
            ctx.db.execute(
                """
                INSERT OR REPLACE INTO branches (
                    name,
                    parent
                ) VALUES (
                    ?,
                    NULL
                )
                """,
                (ctx.branch,),
            )
            return

        existing_branch = ctx.db.execute(
            "SELECT parent FROM branches WHERE name = ?", (ctx.branch,)
        ).fetchone()
        if existing_branch is not None:
            raise SystemExit(
                f"{RED}"
                f"Cannot create branch which already exists: {ctx.branch}"
                f"{RESET}"
            )

        # TODO: what if this branch is already tracked?
        ctx.db.execute(
            """
            INSERT OR REPLACE INTO branches (
                name,
                parent
            ) VALUES (
                ?,
                ?
            )
            """,
            (ctx.branch, root_branch),
        )


def collapse(ctx: Context) -> None:
    # TODO: this should do something like
    # - find the parent of the provided branch
    #   - error if it's the root (aka: no parent)
    # - for each branch directly above this one on the stack:
    #   - set that branch's parent to ctx.branch's parent
    #     - but explicitly use `since=...` to not take the parent branch's changes
    #   - restack it
    # - then delete the current branch
    # - then do a restack like normal on the rest of the stack
    pass


def restack(ctx: Context) -> None:
    with current_repo_state(ctx.repo_root):
        for branch in get_branches_in_stack(ctx.db, ctx.branch):
            if branch.parent is None:
                # Can't restack something which doesn't have a parent!
                continue

            print(f"Restacking {branch.name} onto {branch.parent}...")
            rebase(ctx.repo_root, branch.name, branch.parent)


def main(args: list[str]) -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("create", "collapse", "restack"))
    parser.add_argument("--branch", default=None)
    namespace = parser.parse_args(args[1:])

    command: str = namespace.command

    repo_root = find_repo_root(Path.cwd())
    db = get_db(repo_root)
    branch: str | None = namespace.branch
    if branch is None:
        branch = get_current_branch(repo_root)

    ctx = Context(
        branch=branch,
        db=db,
        repo_root=repo_root,
    )
    with db:
        if command == "create":
            create(ctx)
        elif command == "collapse":
            collapse(ctx)
        elif command == "restack":
            restack(ctx)
        db.commit()


if __name__ == "__main__":
    main(sys.argv)
