#!/usr/bin/env bash

cat << EndOfMessage
{
  inputs = {
    flake-utils.url = "github:numtide/flake-utils";
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
  };

  outputs = {self, flake-utils, nixpkgs}:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
      in
      rec {
        defaultPackage = pkgs.mkShell {
	  packages = [
	    # TODO: place inputs here
          ];
        };
      }
    );
}
EndOfMessage